name: build

on:
  push:
    branches: [ '*' ]

jobs:
  build:
    strategy:
      matrix:
        platform:
        # exe is build for x64
        # - python: x86
        #   wheel: win32
        - python: x64

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: "sudo apt-get install gcc make libffi-dev pkg-config zlib1g-dev libbz2-dev libsqlite3-dev libncurses5-dev libexpat1-dev libssl-dev libgdbm-dev tk-dev libgc-dev python-cffi liblzma-dev libncursesw5-dev"

    - run: "make"

    - run: 'find . -iname pypy -print'
